import type { Metadata } from 'next';
import Link from '@/app/site-link';
import { getSiteSettings } from '@/lib/site-repository';
import { DEFAULT_CONTACT_EMAIL } from '@/lib/site-contact';
export const dynamic = 'force-dynamic';
export const metadata: Metadata = { title: 'Privacidad | Multiservices Laredo', alternates: { canonical: '/privacidad' } };
export default async function PrivacyPage() {
  let email = DEFAULT_CONTACT_EMAIL;
  try { email = (await getSiteSettings()).contactEmail; } catch { /* Public contact fallback. */ }
  return <main className="privacy-page"><Link href="/">← Multiservices Laredo</Link><h1>Aviso de privacidad</h1><p>Actualizado: 7 de septiembre de 2026 · <a href="#english" lang="en">Read in English</a></p>
    <section><h2>Datos y propósito</h2><p>Multiservices Laredo recibe los datos que escribes en sus formularios: nombre, teléfono, correo, empresa y necesidad de personal, o información de candidatura, disponibilidad, mensajes y CV opcional. Los utiliza para revisar solicitudes, responder y dar seguimiento a oportunidades de empleo o servicios. El envío queda registrado con fecha, consentimiento y folio.</p><p>No incluyas números de seguro social, datos bancarios ni documentos de identidad en estos formularios.</p></section>
    <section><h2>Acceso y proveedores</h2><p>Las solicitudes se guardan en la plataforma de alojamiento. El acceso a los CV requiere una sesión y permisos del equipo. Los proveedores de alojamiento y, cuando esté habilitado, de correo procesan la información necesaria para operar el sitio. Las confirmaciones por correo incluyen el folio; los avisos internos remiten al portal y no adjuntan el CV.</p><p>Si eliges WhatsApp, correo, mapas o redes sociales, se abre un servicio externo sujeto a sus propias prácticas de privacidad.</p></section>
    <section><h2>Conservación y solicitudes sobre tus datos</h2><p>Las solicitudes y CV permanecen guardados para su seguimiento; este sitio no aplica un borrado automático por antigüedad. Para consultar, corregir o solicitar la eliminación de tus datos, escribe a <a href={`mailto:${email}`}>{email}</a> e incluye tu folio si lo tienes. El equipo podrá pedir información para verificar que la solicitud te corresponde.</p></section>
    <section><h2>Medición y seguridad</h2><p>La página cuenta vistas y clics de contacto por día y tipo de página. Esta medición no utiliza cookies, identificadores de visitantes, contenido de formularios ni parámetros de la dirección web. Respeta las señales Do Not Track y Global Privacy Control. Para limitar abuso se utilizan temporalmente identificadores derivados de la dirección IP; el alojamiento puede mantener sus propios registros técnicos. El portal utiliza una cookie necesaria para mantener la sesión.</p></section>
    <section id="english" lang="en"><h2>Privacy notice</h2><p>Multiservices Laredo collects the information you provide: name, phone, email, company and staffing needs, or application details, availability, messages and an optional résumé. We use it to review and follow up on employment or service requests. Submissions are saved with a reference, timestamp and consent. Do not submit Social Security numbers, banking details or identity documents.</p><p>Requests are stored by our hosting platform. Résumé access requires an authorized team session. Hosting providers and, when enabled, the email provider process information needed to operate the website. Email receipts include a reference; internal alerts link to the portal and do not attach résumés. External links such as WhatsApp, email, maps and social media have their own privacy practices.</p><p>Requests and résumés remain saved for follow-up; this website does not automatically delete them based on age. To request access, correction or deletion, contact <a href={`mailto:${email}`}>{email}</a>, including your reference if available. The team may need information to verify your request.</p><p>We count page views and contact clicks by day and page category, without analytics cookies, visitor identifiers, form contents or URL parameters. This measurement respects Do Not Track and Global Privacy Control. Temporary identifiers derived from IP addresses help limit abuse; the hosting provider may keep technical logs. A necessary cookie maintains portal sessions.</p></section>
    <Link href="/">Volver al inicio / Back to home</Link>
  </main>;
}
