import assert from 'node:assert/strict';
import { test } from 'node:test';

// Writes synthetic records only to an explicitly opted-in loopback development server.
const origin = process.env.TEST_SITE_URL || 'http://localhost:3001';
const enabled = process.env.RUN_LOCAL_WORKFLOWS === '1';
if (enabled) assert.ok(['localhost', '127.0.0.1'].includes(new URL(origin).hostname), 'Never run mutation tests against production');
const jsonRequest = (path, data, cookie = '') => fetch(`${origin}${path}`, { method: 'POST', headers: { origin, 'content-type': 'application/json', cookie }, body: JSON.stringify(data) });
const password = 'Local-only-test-password-2026!';

test('local workflow: admin, job, PDF application, inquiry, metrics, authorization and logout', { skip: !enabled }, async () => {
  let response = await jsonRequest('/api/portal/auth/setup', { displayName: 'Administrador de prueba', email: 'admin@example.test', password, confirmPassword: password, activationCode: 'Local-test-activation-2026-only' });
  if (response.status !== 201) response = await jsonRequest('/api/portal/auth/login', { email: 'admin@example.test', password });
  assert.equal(response.ok, true, await response.clone().text());
  const cookie = response.headers.get('set-cookie').split(';')[0];
  const id = crypto.randomUUID();
  response = await jsonRequest('/api/portal', { action: 'save_job', job: { titleEs: `Vacante de prueba ${id}`, titleEn: 'Test job', slug: `test-${id}`, status: 'published', descriptionEs: 'Prueba local de operación', requirementsEs: 'Datos sintéticos', location: 'Laredo, TX', openings: 1 } }, cookie);
  assert.equal(response.status, 200, await response.clone().text());
  const snapshot = (await response.json()).snapshot;
  const job = snapshot.jobs.find(x => x.slug === `test-${id}`);
  assert.ok(job);
  assert.equal((await fetch(`${origin}/vacantes/${job.slug}`)).status, 200);
  const form = new FormData();
  for (const [key, value] of Object.entries({ name: 'Candidato de prueba', phone: '9565550100', email: `candidate-${id}@example.test`, consent: 'yes', role: 'Test', jobId: job.id, startedAt: String(Date.now() - 5000), submissionKey: id })) form.set(key, value);
  form.set('resume', new File(['%PDF-1.4\n1 0 obj<</Type/Catalog>>endobj\n%%EOF'], 'test.pdf', { type: 'application/pdf' }));
  const simultaneous = await Promise.all([1,2].map(() => fetch(`${origin}/api/applications`, { method: 'POST', headers: { origin }, body: form })));
  assert.deepEqual(simultaneous.map(x => x.status).sort(), [200,201]);
  const receipts = await Promise.all(simultaneous.map(x => x.json()));
  assert.equal(receipts[0].reference, receipts[1].reference);
  const applicationReference = receipts[0].reference;
  response = await fetch(`${origin}/api/applications`, { method: 'POST', headers: { origin }, body: form });
  assert.equal((await response.json()).reference, applicationReference);
  const portal = await (await fetch(`${origin}/api/portal`, { headers: { cookie } })).json();
  const candidate = portal.snapshot.applications.find(x => x.reference === applicationReference);
  assert.ok(candidate);
  response = await fetch(`${origin}/api/portal/resume/${candidate.id}`, { headers: { cookie } });
  assert.equal(response.status, 200);
  assert.equal(response.headers.get('content-type'), 'application/pdf');
  assert.match(await response.text(), /^%PDF-/);
  assert.notEqual((await fetch(`${origin}/api/portal/resume/${candidate.id}`)).status, 200);
  response = await jsonRequest('/api/portal', { action: 'application_status', id: candidate.id, status: 'contacted' }, cookie);
  assert.equal(response.status, 200);
  assert.equal((await response.json()).snapshot.applications.find(x => x.id === candidate.id).status, 'contacted');
  const employer = new FormData();
  for (const [key, value] of Object.entries({ name: 'Contacto de prueba', company: 'Empresa de prueba', phone: '9565550100', email: `company-${id}@example.test`, need: 'Solicitamos personal para una prueba local', consent: 'yes', startedAt: String(Date.now() - 5000), submissionKey: `emp-${id}` })) employer.set(key, value);
  assert.equal((await fetch(`${origin}/api/inquiries`, { method: 'POST', headers: { origin: 'https://other.example' }, body: employer })).status, 403);
  response = await fetch(`${origin}/api/inquiries`, { method: 'POST', headers: { origin }, body: employer });
  assert.equal(response.status, 201, await response.clone().text());
  const inquiryReference = (await response.json()).reference;
  const duplicates = await Promise.all([1,2].map(() => fetch(`${origin}/api/inquiries`, { method: 'POST', headers: { origin }, body: employer }).then(r => r.json())));
  assert.ok(duplicates.every(x => x.reference === inquiryReference));
  assert.equal((await fetch(`${origin}/api/portal/operations`)).status, 403);
  const metricsResponse = await jsonRequest('/api/metrics', { event: 'page_view', path: '/' });
  assert.equal(metricsResponse.status, 204);
  assert.equal((await jsonRequest('/api/metrics', { event: 'email_click', path: '/portal?secret=test' })).status, 400);
  const operations = await (await fetch(`${origin}/api/portal/operations`, { headers: { cookie } })).json();
  const inquiry = operations.inquiries.find(x => x.reference === inquiryReference);
  assert.ok(inquiry);
  assert.ok(operations.metrics.some(x => x.event === 'page_view' && x.total > 0));
  assert.equal(operations.emailConfigured, false);
  assert.ok(operations.notifications.some(x => x.status === 'pending' && x.total >= 4));
  assert.equal((await jsonRequest('/api/portal/operations', { action: 'inquiry_status', id: inquiry.id, status: 'proposal' }, cookie)).status, 200);
  assert.equal((await jsonRequest('/api/portal/operations', { action: 'retry_notifications' }, cookie)).status, 409);
  assert.equal((await jsonRequest('/api/portal/auth/reset', { action: 'request', email: 'admin@example.test' })).status, 503);
  assert.equal((await jsonRequest('/api/portal/auth/reset', { action: 'complete', token: 'wrong', password, confirmPassword: password })).status, 400);
  // Close the test job; public detail and submissions must stop accepting it.
  assert.equal((await jsonRequest('/api/portal', { action: 'save_job', job: { ...job, status: 'closed' } }, cookie)).status, 200);
  assert.equal((await fetch(`${origin}/vacantes/${job.slug}`)).status, 404);
  assert.equal((await jsonRequest('/api/portal/auth/logout', {}, cookie)).status, 200);
  assert.equal((await fetch(`${origin}/api/portal`, { headers: { cookie } })).status, 401);
});
