'use client';
import { FormEvent,useCallback,useEffect,useState } from 'react';
type User={id:string;displayName:string;email:string;role:string;status:string;version:number};
type Team={users:User[];invites:{id:string;email:string;role:string;expiresAt:string}[];activity:{actorEmail:string;summary:string;createdAt:string}[];pending:{candidates:number;companies:number}};
export default function TeamPanel({summary=false}:{summary?:boolean}){
  const [data,setData]=useState<Team|null>(null),[message,setMessage]=useState(''),[link,setLink]=useState(''),[busy,setBusy]=useState(false);
  const read=useCallback(async()=>{const r=await fetch('/api/portal/team');if(!r.ok)throw new Error('No pudimos cargar el equipo.');return await r.json() as Team;},[]);
  useEffect(()=>{let active=true;const update=()=>{if(document.visibilityState==='visible')void read().then(x=>{if(active)setData(x);}).catch(e=>{if(active)setMessage(e.message);});};update();const timer=window.setInterval(update,60000);window.addEventListener('focus',update);return()=>{active=false;clearInterval(timer);window.removeEventListener('focus',update);};},[read]);
  async function act(payload:object){setBusy(true);setMessage('');setLink('');try{const r=await fetch('/api/portal/team',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const result=await r.json() as {error?:string;url?:string};if(!r.ok)throw new Error(result.error);if(result.url)setLink(result.url);setData(await read());setMessage('Cambio guardado.');}catch(e){setMessage(e instanceof Error?e.message:'No pudimos guardar.');}finally{setBusy(false);}}
  function invite(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);void act({action:'invite',email:form.get('email'),role:form.get('role')});}
  if(summary)return <section className="portal-panel operations-panel"><h2>Requieren atención</h2>{data?<div className="operations-counts"><span><b>{data.pending.candidates}</b> candidatos nuevos</span><span><b>{data.pending.companies}</b> empresas por contactar</span></div>:<p>{message||'Cargando pendientes…'}</p>}<p>Consulta Candidatos o Empresas y resultados para darles seguimiento.</p></section>;
  return <><section className="portal-panel operations-panel"><h1>Equipo y accesos</h1><p>Cada persona utiliza su cuenta. Los cambios de permisos cierran sus sesiones anteriores.</p>{message&&<p role="status">{message}</p>}<form onSubmit={invite} className="operations-filters"><label>Correo del colaborador<input name="email" type="email" required maxLength={254}/></label><label>Permisos<select name="role"><option value="recruiter">Reclutamiento: candidatos y CV</option><option value="editor">Editor: vacantes, textos y fotos</option></select></label><button className="portal-primary" disabled={busy}>Crear invitación</button></form>{link&&<div className="invitation-result"><p>Comparte este enlace únicamente con el colaborador indicado. Vence en 48 horas y permite crear su contraseña. No se envía automáticamente.</p><label>Enlace de activación<input readOnly value={link}/></label><button className="portal-secondary" onClick={()=>void navigator.clipboard.writeText(link).then(()=>setMessage('Enlace copiado.')).catch(()=>setMessage('Selecciona el enlace y cópialo manualmente.'))}>Copiar enlace</button></div>}
    {data?.users.map(user=><article className="inquiry-card" key={user.id}><h2>{user.displayName}</h2><p>{user.email}</p>{user.role==='owner'?<p>Administrador · cuenta protegida</p>:<form className="operations-filters" onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);if(window.confirm('Se cerrarán las sesiones actuales de este colaborador. ¿Guardar el cambio?'))void act({action:'update_user',id:user.id,version:user.version,role:form.get('role'),status:form.get('status')});}} key={`${user.id}-${user.version}`}><label>Permisos<select name="role" defaultValue={user.role}><option value="recruiter">Reclutamiento</option><option value="editor">Editor</option></select></label><label>Acceso<select name="status" defaultValue={user.status}><option value="active">Activo</option><option value="disabled">Suspendido</option></select></label><button disabled={busy} className="portal-secondary">Guardar acceso</button></form>}</article>)}
    <h2>Invitaciones pendientes</h2>{data?.invites.map(item=><article className="inquiry-card" key={item.id}><p>{item.email} · {item.role==='editor'?'Editor':'Reclutamiento'} · vence {new Date(item.expiresAt).toLocaleString('es-US')}</p><button className="portal-secondary" disabled={busy} onClick={()=>void act({action:'revoke_invite',id:item.id})}>Revocar invitación</button></article>)}{data&&!data.invites.length&&<p>No hay invitaciones pendientes.</p>}</section>
    <section className="portal-panel operations-panel"><h2>Actividad reciente</h2><p>Últimos 100 movimientos del equipo.</p>{data?.activity.map((item,i)=><article className="activity-entry" key={i}><strong>{item.summary}</strong><span>{item.actorEmail}</span><small>{new Date(item.createdAt).toLocaleString('es-US')}</small></article>)}</section></>;
}
