export const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS tenants (
    id TEXT PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS memberships (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL REFERENCES tenants(id),
    user_id TEXT,
    email TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'editor',
    created_at TEXT NOT NULL
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_memberships_tenant_email ON memberships(tenant_id, email)`,
  `CREATE INDEX IF NOT EXISTS idx_memberships_user_id ON memberships(user_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_memberships_tenant_user ON memberships(tenant_id, user_id) WHERE user_id IS NOT NULL`,
  `CREATE TABLE IF NOT EXISTS media_assets (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL REFERENCES tenants(id),
    object_key TEXT NOT NULL UNIQUE,
    filename TEXT NOT NULL,
    content_type TEXT NOT NULL,
    size_bytes INTEGER NOT NULL,
    alt_es TEXT NOT NULL DEFAULT '',
    alt_en TEXT NOT NULL DEFAULT '',
    visibility TEXT NOT NULL DEFAULT 'public',
    created_by TEXT,
    created_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_media_tenant_created ON media_assets(tenant_id, created_at)`,
  `CREATE TABLE IF NOT EXISTS site_settings (
    tenant_id TEXT PRIMARY KEY REFERENCES tenants(id),
    hero_line_1_es TEXT NOT NULL,
    hero_accent_es TEXT NOT NULL,
    hero_line_2_es TEXT NOT NULL,
    hero_lead_es TEXT NOT NULL,
    hero_line_1_en TEXT NOT NULL,
    hero_accent_en TEXT NOT NULL,
    hero_line_2_en TEXT NOT NULL,
    hero_lead_en TEXT NOT NULL,
    contact_phone TEXT NOT NULL,
    contact_whatsapp TEXT NOT NULL,
    contact_email TEXT NOT NULL,
    hero_media_id TEXT REFERENCES media_assets(id),
    transport_media_id TEXT REFERENCES media_assets(id),
    operations_media_id TEXT REFERENCES media_assets(id),
    updated_at TEXT NOT NULL,
    updated_by TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS jobs (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL REFERENCES tenants(id),
    slug TEXT NOT NULL,
    title_es TEXT NOT NULL,
    title_en TEXT NOT NULL,
    summary_es TEXT NOT NULL DEFAULT '',
    summary_en TEXT NOT NULL DEFAULT '',
    description_es TEXT NOT NULL DEFAULT '',
    description_en TEXT NOT NULL DEFAULT '',
    requirements_es TEXT NOT NULL DEFAULT '',
    requirements_en TEXT NOT NULL DEFAULT '',
    location TEXT NOT NULL DEFAULT 'Laredo, TX',
    shift TEXT NOT NULL DEFAULT 'Por confirmar',
    employment_type TEXT NOT NULL DEFAULT 'Temporal / proyecto',
    pay_min REAL,
    pay_max REAL,
    pay_unit TEXT NOT NULL DEFAULT 'hora',
    openings INTEGER NOT NULL DEFAULT 1,
    status TEXT NOT NULL DEFAULT 'draft',
    featured INTEGER NOT NULL DEFAULT 0,
    sort_order INTEGER NOT NULL DEFAULT 0,
    published_at TEXT,
    closes_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    created_by TEXT,
    updated_by TEXT
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_jobs_tenant_slug ON jobs(tenant_id, slug)`,
  `CREATE INDEX IF NOT EXISTS idx_jobs_tenant_status_order ON jobs(tenant_id, status, sort_order)`,
  `CREATE INDEX IF NOT EXISTS idx_jobs_status_published ON jobs(status, published_at)`,
  `CREATE TABLE IF NOT EXISTS applications (
    id TEXT PRIMARY KEY,
    reference TEXT NOT NULL UNIQUE,
    submission_key TEXT NOT NULL,
    tenant_id TEXT NOT NULL REFERENCES tenants(id),
    job_id TEXT REFERENCES jobs(id),
    role_interest TEXT NOT NULL,
    full_name TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT NOT NULL,
    city TEXT NOT NULL DEFAULT '',
    availability TEXT NOT NULL DEFAULT '',
    message TEXT NOT NULL DEFAULT '',
    resume_key TEXT,
    resume_filename TEXT,
    status TEXT NOT NULL DEFAULT 'new',
    source TEXT NOT NULL DEFAULT 'website',
    consent_at TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_applications_tenant_submission ON applications(tenant_id, submission_key)`,
  `CREATE INDEX IF NOT EXISTS idx_applications_tenant_status_created ON applications(tenant_id, status, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_applications_job_created ON applications(job_id, created_at)`,
  `CREATE TABLE IF NOT EXISTS rate_limits (
    key TEXT PRIMARY KEY,
    hits INTEGER NOT NULL DEFAULT 0,
    expires_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_rate_limits_expires ON rate_limits(expires_at)`,
  `CREATE TABLE IF NOT EXISTS audit_logs (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL REFERENCES tenants(id),
    actor_id TEXT,
    actor_email TEXT NOT NULL,
    action TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    summary TEXT NOT NULL,
    created_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_audit_tenant_created ON audit_logs(tenant_id, created_at)`,
  `PRAGMA optimize`,
] as const;
